### PR TITLE
Licensing and contributors

### PR DESCRIPTION
**Pull request by paoolo**
@kgadek, @mjkonarski please review it.

### CODE REVIEW

**Comment by kgadek** [comment]
Since we've used beer-ware, you are free to do anything you like. Thanks for pinging us! :+1:

…or it appears to be so. [IANAL](https://en.wikipedia.org/wiki/IANAL), so I'm not sure if beer-ware & MIT are compatible (the former gives away all rights, the latter gives slightly more restricted ones). If that's not a case and that is a problem for you, I would have no problem with relicensing the Amber to MIT (or BSD-3, which is equivalent AFAIK) as long as @mjkonarski agrees to do so.

A small tip: AFAIR in case of multiple licenses in one file, usually you add a note which part of a project is licensed under which one.

**Comment by paoolo** [comment]
@kgadek thank you for your response. I would like to use only one license, so only one will be in `LICENSE.md` when this PR will be merged.

**Comment by kgadek** [comment]
If you want only one license, then Amber shall be relicensed to MIT. So let be it.

You'll probably want to merge/cherry-pick [kgadek/Amber:2f9440524bdd](https://github.com/kgadek/Amber/commit/2f9440524bdd775bae1c8bf2eb284b4c85523e14).

**Comment by paoolo** [comment]
Thank you for your responses.

**Pull request merged**
